### ISSUE TITLE
Incorrect names in internet draft reference XML

### ISSUE THREAD

**Issue by reschke** [ietf-tools/bibxml-service#315] opened 2022-10-27 04:57 UTC
### Describe the issue

https://bib.ietf.org/public/rfc/bibxml-ids/reference.I-D.iab-xml2rfcv2.xml

has

~~~
<author fullname="Julian F. Reschke" initials="F." surname="Julian Reschke"/>
~~~

This is a regression.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment] 2022-10-27 05:46
Thanks @reschke , this may be an issue in the recent initials processing code. We'll fix this.

* https://github.com/relaton/relaton-ietf/issues/109

**Comment by rjsparks** [comment] 2022-10-27 13:57
See also https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml
where it claims `<author fullname="Henrik Levkowetz" surname="Henrik Levkowetz">`

**Comment by ronaldtse** [comment] 2022-10-27 14:01
Thanks @rjsparks !

**Comment by stefanomunarini** [comment] 2022-11-22 20:33
Can we close this @reschke ?

**Comment by rjsparks** [comment] 2022-11-22 22:35
@stefanomunarini : No - it's not fixed. It may have moved around a little, but what's coming out right now still isn't right:
`    <author fullname="Julian F. Reschke" initials="F." surname="Reschke"/>`
Note that what is coming from the datatracker at https://datatracker.ietf.org/doc/bibxml3/reference.I-D.iab-xml2rfcv2.xml is:
`      <author initials="J." surname="Reschke" fullname="Julian Reschke">`
Note the value of `initials`.

**Comment by ronaldtse** [comment] 2022-11-23 06:02
@rjsparks @reschke The problem seems to lie with the authoritative source dataset obtained from the Datatracker archive:

```sh
$ rsync -avcizxL rsync.ietf.org::bibxml-ids/reference.I-D.draft-iab-xml2rfcv2* .
receiving file list ... done
>f+++++++ reference.I-D.draft-iab-xml2rfcv2-00.xml
>f+++++++ reference.I-D.draft-iab-xml2rfcv2-01.xml
>f+++++++ reference.I-D.draft-iab-xml2rfcv2-02.xml
$ cat reference.I-D.draft-iab-xml2rfcv2-02.xml
```

The file contains this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<reference anchor="I-D.iab-xml2rfcv2">
   <front>
      <title>The &quot;xml2rfc&quot; Version 2 Vocabulary</title>
      <author fullname="Julian F. Reschke">
	 </author>
      <date month="September" day="16" year="2015" />
      <abstract>
	 <t>This document defines the &quot;xml2rfc&quot; version 2 vocabulary: an XML-based language used for writing RFCs and Internet-Drafts.

 Version 2 represents the state of the vocabulary (as implemented by several tools and as used by the RFC Editor) around 2014.

 This document obsoletes RFC 2629.
	 </t>
      </abstract>
   </front>
   <seriesInfo name="Internet-Draft" value="draft-iab-xml2rfcv2-02" />
   <format type="TXT" target="https://www.ietf.org/archive/id/draft-iab-xml2rfcv2-02.txt" />
</reference>
```

The relevant lines are:
```xml
      <author fullname="Julian F. Reschke">
	 </author>
```

Notice that the `01` version is:
```xml
      <author initials="J." surname="Reschke" fullname="Julian Reschke">
         </author>
```

And `00` version:
```xml
      <author initials="J." surname="Reschke" fullname="Julian Reschke">
         </author>
```

From the `02` version, which is what the unversioned reference points to, it would be difficult to obtain the desired content.

**Comment by reschke** [comment] 2022-11-23 06:43
2 cents. I don't know how this broke, and why. But it seems pretty clear that we have a lack of test coverage.

If somebody reports broken references, add that reference to your test suite so you can be sure when it is fixed, and that it stays fixed.

**Comment by rjsparks** [comment] 2022-11-23 17:42
High level point: It is a _problem_ that you produce output that is different from what the datatracker provides. "Fixing" what comes out of the datatracker is not something this system should be doing at all.

Interestingly, at the moment:
```
% curl https://datatracker.ietf.org/doc/bibxml3/reference.I-D.iab-xml2rfcv2.xml | grep author
      <author initials="J." surname="Reschke" fullname="Julian Reschke">
      </author>
```
And it does return the bibxml for `02`.  I'll investigate why the copy at the rsync point is not the same.

**Comment by rjsparks** [comment] 2022-11-23 18:24
this turns out to be related to https://github.com/ietf-tools/datatracker/pull/4470. We created the initial bibxml-ids backing store in Jan 22, before that change was made. There are quite a number of references that would change because of it. I'm running the update over the backing store now.

**Comment by rjsparks** [comment] 2022-11-23 18:54
That update is complete.

**Comment by ronaldtse** [comment] 2022-11-24 01:13
> High level point: It is a problem that you produce output that is different from what the datatracker provides. "Fixing" what comes out of the datatracker is not something this system should be doing at all.

Thank you, I agree that reproducing the data identically from the datatracker is the intended goal. And thank you for updating the backing store. We will ensure that this is the case going forward.

> If somebody reports broken references, add that reference to your test suite so you can be sure when it is fixed, and that it stays fixed.

Thanks @reschke , this is certainly something we have been doing when issues arise.

**Comment by ronaldtse** [comment] 2022-12-06 23:53
Following the update at datatracker, this issue has been fixed. @reschke can you confirm that the case is closed? Thanks.

The corresponding tests have been added here: https://github.com/relaton/relaton-ietf/commit/55d31ea31f0789df4230ef86e2275bc1357079e8

**Comment by reschke** [comment] 2022-12-07 06:12
It has *changed*. The output now is:

~~~
<author initials="J." surname="Reschke" fullname="Julian Reschke">
~~~

but the fullname doesn't match what's on the actual document (https://www.ietf.org/archive/id/draft-iab-xml2rfcv2-02.txt).

Not sure whether it ever did.

**Comment by ronaldtse** [comment] 2022-12-07 06:34
@reschke this is the XML on the actual document on datatracker as provided by @rjsparks :
https://datatracker.ietf.org/doc/bibxml3/reference.I-D.iab-xml2rfcv2.xml:

```xml
<author initials="J." surname="Reschke" fullname="Julian Reschke">
```

**Comment by reschke** [comment] 2022-12-07 07:27
Ack. I just pointed out that the information is not sufficient to recreate the "Authors" section in that draft. I don't know whether that was the case somewhere in the past.

**Comment by ronaldtse** [comment] 2022-12-07 09:09
Thanks @reschke , I will leave the question on how the datatracker's BibXML reflects the content of the source RFC XML to @rjsparks . Closing this for now.

**Closed by ronaldtse** 2022-12-07 09:09 UTC
Labels: bug
