### ISSUE TITLE
Remove preamble in XML responses

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/bibxml-service#275] opened 2022-08-18 13:23 UTC
At #252 we removed the dtd declaration that was added as part of #234.

We also should remove `<?xml version='1.0' encoding='utf-8'?>`.

These snippets are being included by software that did not expect to have to modify the content of the snippet in any way, and users are now having to deal with documents that have that declaration multiple times through the body (once per included reference).

**Comment by ronaldtse** [comment] 2022-08-18 13:45
Thanks for letting us know @rjsparks . 

@stefanomunarini could you please help with this too? Thanks!

**Comment by stefanomunarini** [comment] 2022-08-18 15:47
I'm not sure I am getting this issue. Can you give an example/URL of some entries containing this preamble?

I've checked a few entries, e.g.:
- https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.FIPS.180-4.xml
- https://bib.ietf.org/public/rfc/bibxml-nist/reference.NIST.FIPS.180-4.xml

and none of them seems to be using the `<?xml version='1.0' encoding='utf-8'?>` preamble.

**Comment by rjsparks** [comment] 2022-08-18 16:49
```
rjsparks@undex tmp % curl https://bib.ietf.org/public/rfc/bibxml/reference.RFC.3261.xml --no-progress-meter | head -2
<?xml version='1.0' encoding='utf-8'?>
<reference anchor="RFC3261" target="https://www.rfc-editor.org/info/rfc3261">
```

**Comment by rjsparks** [comment] 2022-08-18 16:50
and
```
rjsparks@undex tmp % curl https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.FIPS.180-4.xml --no-progress-meter | head -2
<?xml version='1.0' encoding='utf-8'?>
<reference anchor="DOI_10.6028_NIST.FIPS.180-4" target="http://dx.doi.org/10.6028/nist.fips.180-4">
```
@stefanomunarini are you perhaps looking at the output directly in your browser? If so, try view-source...

**Comment by stefanomunarini** [comment] 2022-08-18 20:22
> and
> 
> ```
> rjsparks@undex tmp % curl https://bib.ietf.org/public/rfc/bibxml7/reference.DOI.10.6028/NIST.FIPS.180-4.xml --no-progress-meter | head -2
> <?xml version='1.0' encoding='utf-8'?>
> <reference anchor="DOI_10.6028_NIST.FIPS.180-4" target="http://dx.doi.org/10.6028/nist.fips.180-4">
> ```
> 
> @stefanomunarini are you perhaps looking at the output directly in your browser? If so, try view-source...

I was checking using the browser, indeed. Thanks for the quick reply @rjsparks

**Comment by strogonoff** [comment] 2022-08-20 02:17
@stefanomunarini this can be done at relaton-py’s level here: https://github.com/relaton/relaton-py/blob/3c55119b433da0e788d17e98e4853f3bbaff65b8/relaton/serializers/bibxml_string/__init__.py#L33-L34

**Comment by strogonoff** [comment] 2022-08-20 02:22
@stefanomunarini  Actually, it may not require a change in `relaton-py`.

I think these are the options:

- change [`relaton.serializers.bibxml_string.serialize`](https://github.com/relaton/relaton-py/blob/3c55119b433da0e788d17e98e4853f3bbaff65b8/relaton/serializers/bibxml_string/__init__.py#L12-L38): remove the declaration or make it configurable
- stop using `relaton.serializers.bibxml_string` in BibXML service, and instead implement a similar function that takes the output of `relaton.serializers.bibxml.serialize` and does string conversion in whatever way required by the service. I personally suspect this is the best option, since this does not require a new release of `relaton-py` and future changes would be faster.

**Comment by ronaldtse** [comment] 2022-08-24 01:51
I agree with 2. Can we move ahead?

**Comment by strogonoff** [comment] 2022-08-28 07:31
I believe @stefanomunarini is working on it in https://github.com/ietf-tools/bibxml-service/pull/279, may already be ready actually.

**Comment by stefanomunarini** [comment] 2022-08-28 09:41
Confirmed @strogonoff . Waiting for it to be merged

**Comment by strogonoff** [comment] 2022-09-06 17:02
I believe this had been merged

**Closed by strogonoff** 2022-09-06 17:02 UTC
Labels: bug
