### ISSUE TITLE
Validation error with keywords

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#390] opened 2023-12-27 20:38 UTC
### Describe the issue

Recent changes introduce errors with keywords.
For example [RFC 9000](https://bib.ietf.org/get-one/by-docid/?docid=RFC+9000&doctype=IETF&format=bibxml):

```
Could not export this item, the error was: Source data for item RFC 9000 (IETF) didn’t validate (err: 11 validation errors for BibliographicItem keyword -> 0 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 1 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 2 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 3 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 4 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 5 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 6 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 7 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 8 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword -> 9 instance of KeywordType, tuple or dict expected (type=type_error.dataclass; class_name=KeywordType) keyword KeywordType.__init__() takes from 1 to 2 positional arguments but 11 were given (type=type_error))
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment] 2023-12-27 20:40
I've rolled back bibxml.ietf.org to v2023.11.3_1.

**Comment by kesara** [comment] 2023-12-27 20:45
@stefanomunarini I think keyword changes in https://github.com/ietf-tools/bibxml-service/pull/348 are causing this issue.

**Comment by stefanomunarini** [comment] 2024-01-03 08:36
Hi @kesara , did this issue arise after re indexation of the sources? I am trying to understand how to replicate the issue on my local machine, but seem unable to do so. Thanks

**Comment by stefanomunarini** [comment] 2024-01-03 10:14
I think this is the issue @kesara , source data needs to be reindexed for that code to work. Is there a day/time that this update could be released with the least disruption? Indexation of sources takes some time (not sure how long it does in production, as I do not have access to the management GUI, but on my local machine is about 1 hour for all the sources)

**Comment by stefanomunarini** [comment] 2024-01-03 11:22
I can confirm I was able to replicate the issue rolling back to an old commit. Rebuilding the service with the upgraded relaton-py and re indexing the sources fixed the issue. 

Please note: It might take a few minutes for the changes to appear in the GUI after reindexing due to caching.

**Comment by kesara** [comment] 2024-01-03 18:17
@stefanomunarini Thanks for looking at it. Should I wait for #393?

**Comment by stefanomunarini** [comment] 2024-01-04 10:59
Hi @kesara . No #393 should also be merged after upgrading relaton version (it simply list the keywords values, instead of a dictionary of the format `{"content": "value"}`) in the citation details page.

**Closed** 2024-01-04 22:18 UTC
Labels: bug
