### ISSUE TITLE
broken author XML for RFC 8288

### ISSUE THREAD

**Issue by reschke** [ietf-tools/bibxml-service#325] opened 2022-12-29 18:31 UTC
### Describe the issue

See <https://bib.ietf.org/public/rfc/bibxml/reference.RFC.8288.xml>:

~~~
<reference anchor="RFC8288" target="https://www.rfc-editor.org/info/rfc8288">
  <front>
    <title>Web Linking</title>
    <author fullname="M. Nottingham" initials="M." surname="Nottingham"/>
    <author>
      <organization>RFC Publisher</organization>
    </author>
    <date month="October" year="2017"/>
    <abstract>
      <t>This specification defines a model for the relationships between resources on the Web ("links") and the type of those relationships ("link relation types").</t>
      <t>It also defines the serialisation of such links in HTTP headers with the Link header field.</t>
    </abstract>
  </front>
  <seriesInfo name="RFC" value="8288"/>
  <seriesInfo name="DOI" value="10.17487/RFC8288"/>
  <format target="https://www.rfc-editor.org/info/rfc8288" type="TXT"/>
</reference>
~~~

Note the entry for "RFC Editor".

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ronaldtse** [comment] 2022-12-31 14:28
Thank you @reschke , this is a bug on our side as a regression of #321 . I will open a separate issue to track this.

**Comment by sginoza** [comment] 2023-01-02 18:57
(moving this comment here from #321)

(just to note another example)

It looks like this issue has reappeared. While trying to publish last week, I noticed that "RFC Publisher" is now listed as an author for RFCs. For example, see

https://www.rfc-editor.org/v3test/rfc9333.html#section-12.1
https://www.rfc-editor.org/v3test/rfc9333.xml

It seems that the http://bib.ietf.org/ files contain the "RFC Publisher" data. Examples:

https://bib.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml
https://bib.ietf.org/public/rfc/bibxml/reference.RFC.5234.xml
https://bib.ietf.org/public/rfc/bibxml/reference.RFC.9020.xml

**Comment by ajeanmahoney** [comment] 2023-01-03 14:06
@ronaldtse This issue has delayed the publication of RFCs and needs to be treated as urgent.

**Comment by rjsparks** [comment] 2023-01-03 14:45
@ronaldtse - where are we with versioning? I'm surprised that such a regression affected what the bibxml service renders? What needs to happen to keep such perturbations from propagating before they are accepted?

**Closed** 2023-01-12 13:44 UTC
Labels: bug
