### ISSUE TITLE
Publicly documenting authoritative sources for bib data

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/bibxml-service#271] opened 2022-08-15 16:13 UTC
### Description

It would be good to capture somewhere publicly where the bib data comes from. Somewhere, relaton-data-rfcs, relaton-data-ieee, etc., should be explained--maybe a link off the About page, or maybe there's developer's documentation  in GitHub that can expanded. 

For instance, it has been mentioned in issue discussions that the authoritative data for RFCs comes from rfc-index.xml provided by rfc-editor.org, but I can't find that documented in the code base or any readmes or About pages...

This file is basically an API and it should be tracked. The RPC will be making changes to their database in the next few years, and such existing APIs should be identified and managed. 

Thanks!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajeanmahoney** [comment] 2022-08-15 19:06
I may have made an assumption about how the bibmxl-service pulls RFC bib data. Thus documentation of where the data comes from is even more important.

**Comment by rjsparks** [comment] 2022-08-16 13:21
Digging through older tickets, I relocated this: https://github.com/ietf-tools/bibxml-service/wiki/Data-sources. Is the table still accurate? The discussion of sync from tools.ietf.org needs to be updated.

**Comment by ronaldtse** [comment] 2022-08-16 13:24
@rjsparks yes that page is accurate.

For W3C, we now have an extra repo that contains historic W3C documents since 2002 from the same endpoint (https://github.com/relaton/w3c-tr-archive). Would you be able to help update that row? Thanks!

**Comment by rjsparks** [comment] 2022-08-16 13:24
I note also that links in the documentation have become broken. 
https://bib.ietf.org/static/docs/topics/architecture.html has a link to https://github.com/ietf-ribose/bibxml-service/wiki/Relaton-sources. (which redirects to ietf-tools, but then finds no wiki page - I suspect it was intended to point to Data-sources instead)?

**Comment by rjsparks** [comment] 2022-08-16 13:28
>Would you be able to help update that row? Thanks!
Sure - but we should make it so that you could too. Anton and Vladamir already have the ability to do so, and we'll make sure you do to (I want to confirm with Kesara when his timezone comes online how he's started this config before adding changes).

**Comment by ronaldtse** [comment] 2022-08-16 17:17
Thanks @rjsparks , will wait for @kesara

**Comment by kesara** [comment] 2022-08-16 22:54
`bibxml-service` wiki is configured so that it's only editable by people who have push (write) access to this repository.
At the moment Anton and Vladamir have that access.
These settings were inherited from `ietf-ribose`.

**Comment by ronaldtse** [comment] 2022-08-17 01:39
Thanks @kesara , I confirm to have received access to this repo. I believe when the repository was transferred, the permissions given to "Teams" originally assigned were removed, but permissions for individuals remained.

**Comment by strogonoff** [comment] 2022-08-31 05:58
I see the link [in documentation](https://bib.ietf.org/static/docs/topics/architecture.html) was fixed to point to  https://github.com/ietf-tools/bibxml-service/wiki/Data-sources thanks to Ronald. Combining docs and wiki, is documentation lacking?

**Comment by rjsparks** [comment] 2022-08-31 13:32
https://github.com/ietf-tools/bibxml-service/wiki/Data-sources#xml2rfc-mirror-archive is stale.

Would it be hard to add a column to the table pointing to the code that ingests each source? (Labelled "as of version nnn"). Or if not a direct link to the code, at least a sentence that would help someone responsible for one of these sources look to see what the impact of a change to the source will have?

**Comment by ajeanmahoney** [comment] 2022-08-31 15:05
It would also be nice to capture how often data is fetched from each data source.

**Comment by ronaldtse** [comment] 2022-09-14 15:53
@rjsparks @ajeanmahoney  I've fixed the stale link, added links to the sources of the software, and added a frequency column.

**Comment by ronaldtse** [comment] 2022-09-14 16:34
@ajeanmahoney @rjsparks is the documentation now sufficient to close this issue? Thanks.

**Comment by rjsparks** [comment] 2022-09-14 17:55
@ronaldtse : Close.

There are still some /ietf-ribose/ repositories called out that have moved already to /ietf-tools/, and we need to address https://github.com/ietf-ribose/bibxml-data-misc which has not moved yet?

**Comment by kesara** [comment] 2022-09-15 21:11
bibxml-data-misc repository has been transferred to ietf-tools: https://github.com/ietf-tools/bibxml-data-misc

**Closed** 2022-09-16 17:38 UTC
Labels: enhancement
